hashicorp/swingset

README.md
components/knobs-component/index.jsx
components/knobs-component/style.module.css
components/props-table/index.jsx

This PR adds two new things:
This new type will render the default value into a textarea as json if using the knobs component. This will accept more complex props, and allow basic, if awkward, editing in the knobs interface. This is kind of a "last resort" rendering option which is not recommended. **Example:**
This new option for the `props.json5` file will add an annotation to the props table intended for array props that allows the author to describe the type(s) accepted by the array in a freeform manner. **Example:**

Better support for array and other more complex props

---

README.md
components-loader.js
components/live-component/index.jsx
components/live-component/style.module.css
components/props-table/index.jsx
components/shared.module.css
example/components/button/docs.mdx
example/components/button/index.jsx
example/components/button/props.js
example/components/button/props.json5
getStaticProps.js
package-lock.json
package.json
page.jsx
style.module.css

A couple goals with this PR:
- Make deeply nested properties document-able, including a mix of arrays and objects
- Clean up and improve the prop names to make things more clear
This is a very breaking change, specific API breakages notes below:
- `props.json5` is now `props.js`
- nested properties now must be placed under a `properties` key rather than being directly nested - this key can take either an array of object depending on the nested value type, and can be deep nested indefinitely
- `defaultValue` is now named `testValue`, and can accept any normal javascript data structure
- `itemType` is now deprecated, as arrays can be provided to the `properties` key at any level and documented by individual type
- a new optional key, `default` has been added to specify when a property has a …

Improve Properties Interface

---

.circleci/config.yml
example/components/button/docs.mdx
example/components/button/package.json
getStaticProps.js

This PR exposes `package.json` data to the docs page scope of each component.
It does this by trying to read and parse `${component.path}/package.json`. If this file is present and is valid `json`, then its contents will be exposed in the docs page scope as `packageJson` (similar to the exposure of `componentProps`).
If the `package.json` file is not present, then `packageJson` in the docs page scope will be undefined. If the `package.json` file is present but is not valid `json`, then `swingset` will throw an error.

Expose package.json in components' docs page scopes 

---

getStaticProps.js
package-lock.json
package.json

Went to use `0.5.0` in `react-components` and immediately realized I'd borked some things in #13. This PR fixes those things.
It also adds a `release:pre` script to make it easier to cut pre-releases. I've tested a pre-release with the patches in this PR in [`react-components#124`](https://github.com/hashicorp/react-components/pull/124).

Fix issues with packageJson

---

style.module.css

Good catch by @zchsh! When I added an anchor element into the sidebar `li` the full visual element wasn't clickable. Adjusted styling so anywhere you click is the link.

fix: move sidebar styles so the full list element is clickable

---

README.md
getStaticProps.js

Enables consumers to supply `mdxOptions` to `createStaticProps`. 
Use cases include: applying any of our internal remark / rehype plugins. [On learn](https://github.com/hashicorp/learn/pull/3124/commits/6bc04abd7f801130a6b1e7c95d4bc5771f635591#diff-8ab0398cb55afb95f74d08c55474623b161c2a948d7b72dc8d0a2ae9bb3ce90a), we're using it to add anchor links, custom alerts, and code highlighting.

Add mdx options to `createStaticProps`

---

utils/url-state.js

* enables swingset to be properly confiugured on a non-index route eg `/components`

bugfix: remove hardcoded `/` from page route

---

components/props-table/style.module.css
components/shared.module.css
examples/basic/package-lock.json
package.json
style.module.css

Fixes https://app.asana.com/0/1100423001970639/1200120445315592
This is a bit messy of a fix, but I think it's important to let swingset consumers impose their own global styles so that the playground accurately represents the native environment where their components live, so hopefully this does the trick by only touching swingset UI elements.
Definitely makes the out-of-the-box styling a little uglier, but this doesn't really matter for our implementation, and we can revisit and spruce it up later if we plan to promote this publicly.

Remove base styling

---

package.json

Allows `next@10.x` to be used as peer dependency, this issue arose when moving to npm 7 for me

fix(deps): update peerDependency version range for next

---

README.md
components-loader.js
examples/basic/components/button/docs.mdx
examples/basic/components/button/index.jsx
page.jsx

Allow access to named exports from the component module, not just the default.

feat: support named exports

---

utils/get-peer-components.js

Fixing up the peerComponents thing after our refactor of the components data structure.

fix: update getPeerComponents to pull from the right spot

---

page.jsx

Ensures that any components passed through as options are also passed through to `DocsPage`. So when we call:
```ts
createPage({ components: { ... } })
```
Any docs pages declared in the `docsRoot` will get access to these components.

feat: pass components to DocsPage

---

.changeset/config.json
.github/workflows/canary-release.yml
package-lock.json
package.json

This PR adds support for Changesets along with canary releases. It _does not_ (yet!) add support for production releases via changesets.

chore(ci): add support for canary releases

---

.changeset/cyan-years-retire.md
package-lock.json
package.json
page.tsx
style.module.css

Currently, `swingset` renders a fixed width sidebar and main content area. Since the sidebar's width is fixed across all screen widths, this constrains the width of the main content area which in turn causes visual bugs on smaller viewports. This complicates visual QA/testing for mobile and tablet.
_Example_
This PR adds a button that, when clicked, hides the sidebar and expands the content area. It's not a particularly elegant implementation, but it gets the job done.
- Navigate to the `react-components` [preview](https://react-components-git-natest-fullscreen-hashicorp.vercel.app/components/nextsteps) (using the canary release)
- Click the fullscreen button and verify that the main content area expands and the sidebar disappears
- Click the fullscreen button again and verify that the …

Enable fullscreen content area in `swingset`

---

.changeset/itchy-bats-exist.md
components-loader.js

This PR ignores `node_modules` folders when resolving the components glob, which allows for nested components in a single package.

feat: ignore node_modules folders when resolving components glob

---

examples/basic/components/button/docs.mdx
examples/basic/components/card/docs.mdx
examples/basic/components/text-input/docs.mdx
examples/basic/components/text/docs.mdx
packages/swingset-theme-hashicorp/src/components/props-table.tsx
packages/swingset-theme-hashicorp/src/index.tsx
packages/swingset/src/get-categories.ts
packages/swingset/src/loader.ts
packages/swingset/src/resolvers/component.ts
packages/swingset/src/types.ts

Adds a new `title` property to the `ComponentEntity`. If `title` is defined in frontmatter, this will use that value. Otherwise, it will fallback to the generated `slug`. Use this value when generating the categories data, and update `swingset-theme-hashicorp` to use the new property.

feat: use `title` from frontmatter in categories data, if defined

---

packages/swingset-theme-hashicorp/src/index.tsx

Updates `swingset-theme-hashicorp` to import its global CSS file first, ensuring any other CSS is concatenated _after_ the global declarations.
fixes https://github.com/hashicorp/swingset/issues/95

fix: ensure global theme CSS is loaded first

---

.gitignore
.vscode/launch.json
CONTRIBUTING.md
packages/swingset/src/loader.ts

Updates the `CONTRIBUTING.md` file with a section on debugging the example app with VSCode. I've also included a `.vsocde/launch.json` file with a configuration for running the example app.

docs: add section on debugging the example app

---

packages/swingset/src/get-nav-tree.ts
packages/swingset/src/types.ts

Consistently using `__type` instead of `type` in all the Nodes

change to `__type`

---

examples/basic/turbo.json
turbo.json

Ensure the example app's outputs are cached by turbo to avoid cached build failures.

fix: add turbo config for example app to configure cache outputs

---

examples/basic/app/(swingset)/swingset/content.mdx
examples/basic/components/button/docs.mdx
examples/basic/mdx-components.js
examples/basic/next.config.mjs
examples/basic/package.json
package-lock.json
packages/swingset-theme-hashicorp/package.json
packages/swingset-theme-hashicorp/src/MDXComponents.tsx
packages/swingset-theme-hashicorp/src/components/code-block/code-block.tsx
packages/swingset-theme-hashicorp/src/components/code-block/copy-button.tsx
packages/swingset-theme-hashicorp/src/components/code-block/helpers.ts
packages/swingset-theme-hashicorp/src/components/code-block/index.tsx
packages/swingset-theme-hashicorp/src/components/code-block/theme.ts
packages/swingset-theme-hashicorp/src/components/live-component/code-theme.tsx
packages/swingset-theme-hashicorp/src/components/live-component/get-file-map.ts
packages/swingset-theme-hashicorp/src/components/live-component/index.tsx
packages/swingset-theme-hashicorp/src/types.ts
packages/swingset-theme-hashicorp/tsconfig.json

🎟️ [Asana Task](https://app.asana.com/0/1100423001970639/1204807557661941/f)
👀 [Preview](https://swingset-example-git-preslive-comp-sandpack-hashicorp.vercel.app/swingset)
This PR adds two new components to `swingset-theme-hashicorp` and exposes them for use in `.mdx` files to any Next.js application that uses App Router + Swingset
This is the component rendered for the mdx `<pre>` tag i.e. 
````markdown
```js
/* Code here */
```
````
However it can also be used directly with a string.
```jsx
<CodeBlock {...props}>
{`
export default function App() {
const data = "World"
return <p>Hello, {data}</p>
}
`}
</Codeblock>
```
It's currently using the `prism-react-renderer` to facilitate syntax highlighting however it's using an arbitrary theme, a follow up Issue to this PR should unify the …

LiveComponent Kickoff 🎉
